[package]
name = "karaoke-rs"
version = "0.3.0"
authors = ["Cory Forsstrom <cforsstrom18@gmail.com>"]
edition = "2018"

[dependencies]
cdg = "0.1"
cdg_renderer = "0.1"
image = "0.10.0"
minimp3 = "0.3.2"
sfml = "0.14.0"
glob = "0.3.0"
id3 = "0.3.0"
failure = "0.1.1"
serde_derive = "1.0.0"
serde = "1"
lazy_static = "1.3.0"
dirs = "1.0.5"
crossbeam-channel = "0.3"
clap = "2.33.0"
rust-embed="4.3.0"
rayon = "1.0"
tera = "0.11"
actix-web = "1.0.0-beta.4"
actix-files = "0.1.0-beta.4"
env_logger = "0.6"

[dependencies.rustbreak]
version = "2.0.0-rc3"
features = ["yaml_enc"]